// Licensed to the Qtyi under one or more agreements.
// The Qtyi licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;

namespace Luna.Tools;

internal sealed class LuaTestFilesSourceWriter : IndentWriter
{
    private readonly ImmutableArray<string> _fileNames;

    public LuaTestFilesSourceWriter(TextWriter writer, TestFilesSourceProductionContext context) : base(writer)
    {
        _fileNames = context.FileNames;
    }

    public static void WriteSource(TextWriter writer, TestFilesSourceProductionContext context) => new LuaTestFilesSourceWriter(writer, context).WriteSource();

    private void WriteSource()
    {
        WriteLine("// <auto-generated />");
        WriteLine();
        WriteLine("#nullable enable");
        WriteLine();
        WriteLine("using System.Collections.Generic;");
        WriteLine();
        WriteLine("namespace TestResources;");
        WriteLine();
        WriteLine("public static class LuaTestFiles");
        this.OpenBlock();

        WriteProperties();
        WriteLine();
        WriteMethod();

        this.CloseBlock();
    }

    private void WriteProperties()
    {
        var flag = true;
        foreach (var fileName in _fileNames)
        {
            if (flag) flag = false;
            else WriteLine();

            var name = Path.GetFileNameWithoutExtension(fileName);
            var staticFieldName = "s_" + CamelCase(name);
            var propertyName = PascalCase(name);
            WriteLine($"private static string {staticFieldName};");
            WriteLine($"public static string {propertyName} => ResourceLoader.GetOrCreateResource(ref {staticFieldName}, \"LuaTestFiles.{fileName}\");");
        }
    }

    private void WriteMethod()
    {
        WriteLine("public static IEnumerable<(string name, string source)> GetAllFiles()");
        this.OpenBlock();

        foreach (var fileName in _fileNames)
        {
            var name = Path.GetFileNameWithoutExtension(fileName);
            var propertyName = PascalCase(name);
            WriteLine($"yield return (\"{fileName}\", {propertyName});");
        }

        this.CloseBlock();
    }
}
