// Licensed to the Qtyi under one or more agreements.
// The Qtyi licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using System.Diagnostics;

namespace Luna.Tools;

internal sealed class MoonScriptTestFilesSourceWriter : IndentWriter
{
    private readonly ImmutableArray<(string input, string output)> _fileNames;

    public MoonScriptTestFilesSourceWriter(TextWriter writer, TestFilesSourceProductionContext context) : base(writer)
    {
        var moonScriptFileNames = context.FileNames.Where(static fileName => string.Equals(Path.GetExtension(fileName), ".moon", StringComparison.OrdinalIgnoreCase));
        var luaFileNames = context.FileNames.Where(static fileName => string.Equals(Path.GetExtension(fileName), ".lua", StringComparison.OrdinalIgnoreCase));

        _fileNames = 
            (from moonScriptFileName in moonScriptFileNames
             join luaFileName in luaFileNames
             on Path.GetFileNameWithoutExtension(moonScriptFileName).ToLowerInvariant() equals Path.GetFileNameWithoutExtension(luaFileName).ToLowerInvariant()
             select (moonScriptFileName, luaFileName))
             .ToImmutableArray();
        Debug.Assert(_fileNames.Length * 2 == context.FileNames.Length);
    }

    public static void WriteSource(TextWriter writer, TestFilesSourceProductionContext context) => new MoonScriptTestFilesSourceWriter(writer, context).WriteSource();

    private void WriteSource()
    {
        WriteLine("// <auto-generated />");
        WriteLine();
        WriteLine("#nullable enable");
        WriteLine();
        WriteLine("using System.Collections.Generic;");
        WriteLine();
        WriteLine("namespace TestResources;");
        WriteLine();
        WriteLine("public static class MoonScriptTestFiles");
        this.OpenBlock();

        WriteProperties();
        WriteLine();
        WriteMethod();

        this.CloseBlock();
    }

    private void WriteProperties()
    {
        var flag = true;
        foreach ((var input, var output) in _fileNames)
        {
            if (flag) flag = false;
            else WriteLine();

            WriteProperty(input, input: true);
            WriteLine();
            WriteProperty(output, input: false);
        }
    }

    private void WriteProperty(string fileName, bool input)
    {
        var name = Path.GetFileNameWithoutExtension(fileName);
        var staticFieldName = "s_" + (input ? "input" : "output") + "_" + CamelCase(name);
        var propertyName = (input ? "Input" : "Output") + "_" + PascalCase(name);
        WriteLine($"private static string {staticFieldName};");
        WriteLine($"public static string {propertyName} => ResourceLoader.GetOrCreateResource(ref {staticFieldName}, \"MoonScriptTestFiles.{fileName}\");");
    }

    private void WriteMethod()
    {
        WriteLine("public static IEnumerable<(string inputName, string inputSource, string outputName, string outputSource)> GetAllFiles()");
        this.OpenBlock();

        foreach ((var input, var output) in _fileNames)
        {
            var inputName = Path.GetFileNameWithoutExtension(input);
            var inputPropertyName = "Input_" + PascalCase(inputName);
            var outputName = Path.GetFileNameWithoutExtension(output);
            var outputPropertyName = "Output_" + PascalCase(outputName);
            WriteLine($"yield return (\"{input}\", {inputPropertyName}, \"{output}\", {outputPropertyName});");
        }

        this.CloseBlock();
    }
}
