// Licensed to the Qtyi under one or more agreements.
// The Qtyi licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using Luna.Compilers.Generators.CSharp;
using LanguageNames = Qtyi.CodeAnalysis.LanguageNames;

namespace Luna.Compilers.Generators.ErrorFacts;

internal sealed class ErrorFactsSourceWriter : IndentWriter
{
    public ErrorFactsSourceWriter(TextWriter writer, CancellationToken cancellationToken) : base(writer, 4, cancellationToken) { }

    public static void WriteMain(TextWriter writer, ImmutableArray<string> codeNames, CancellationToken cancellationToken) => new ErrorFactsSourceWriter(writer, cancellationToken).WriteMain(codeNames);

    private void WriteFileHeader()
    {
        this.WriteLine("// <auto-generated />");
        this.WriteLine();
        this.WriteLine("#nullable enable");
        this.WriteLine();
    }

    private void WriteMain(ImmutableArray<string> codeNames)
    {
        ErrorFactsGenerator.GetCodeNames(codeNames, out var warningCodeNames, out var fatalCodeNames, out var infoCodeNames, out var hiddenCodeNames);

        this.WriteFileHeader();
        this.WriteLine($"namespace Qtyi.CodeAnalysis.{LanguageNames.This}");
        this.OpenBlock();

        this.WriteLine("partial class ErrorFacts");
        this.OpenBlock();

        this.CancellationToken.ThrowIfCancellationRequested();
        this.WriteCategory("Warning", warningCodeNames);
        this.WriteLine();

        this.CancellationToken.ThrowIfCancellationRequested();
        this.WriteCategory("Fatal", fatalCodeNames);
        this.WriteLine();

        this.CancellationToken.ThrowIfCancellationRequested();
        this.WriteCategory("Info", infoCodeNames);
        this.WriteLine();

        this.CancellationToken.ThrowIfCancellationRequested();
        this.WriteCategory("Hidden", hiddenCodeNames);

        this.CloseBlock();

        this.CloseBlock();
    }

    private void WriteCategory(string category, ImmutableArray<string> codeNames)
    {
        this.WriteLine($"public static bool Is{category}(ErrorCode code)");
        this.OpenBlock();

        this.WriteLine("switch (code)");
        this.OpenBlock();

        if (codeNames.Length != 0)
        {
            foreach (var name in codeNames)
            {
                this.Write("case ErrorCode.");
                this.Write(name);
                this.WriteLine(":");
            }
            this.Indent();
            this.WriteLine("return true;");
            this.Unindent();
        }
        this.WriteLine("default:");
        this.Indent();
        this.WriteLine("return false;");
        this.Unindent();

        this.CloseBlock();

        this.CloseBlock();
    }
}
