// Licensed to the Qtyi under one or more agreements.
// The Qtyi licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Immutable;
using Roslyn.Utilities;

namespace Luna.Compilers.Generators.ErrorFacts;

[Obsolete($"Use {nameof(ErrorFactsSourceProducer)} instead.")]
internal sealed class ErrorFactsSourceWriter : IndentWriter
{
    public ErrorFactsSourceProductionContext Context { get; init; }

    public ErrorFactsSourceWriter(TextWriter writer, ErrorFactsSourceProductionContext context)
        : base(writer)
    {
        Context = context;
    }

    public static void WriteMain(TextWriter writer, ErrorFactsSourceProductionContext context) => new ErrorFactsSourceWriter(writer, context).WriteMain();

    private void WriteFileHeader()
    {
        WriteLine("// <auto-generated />");
        WriteLine();
        WriteLine("#nullable enable");
        WriteLine();
    }

    private void WriteMain()
    {
        WriteFileHeader();
        WriteLine($"namespace Qtyi.CodeAnalysis.{Context.ThisLanguageName}");
        this.OpenBlock();

        WriteLine("partial class ErrorFacts");
        this.OpenBlock();

        bool first = true;
        foreach ((var category, var codeNames) in Context.CategorizedErrorCodeNames)
        {
            if (first)
                first = false;
            else
                WriteLine();

            WriteCategory(category, codeNames);
        }

        this.CloseBlock();

        this.CloseBlock();
    }

    private void WriteCategory(string category, ImmutableArray<string> codeNames)
    {
        WriteLine($"public static bool Is{category}(ErrorCode code)");
        this.OpenBlock();

        WriteLine("switch (code)");
        this.OpenBlock();

        if (codeNames.Length != 0)
        {
            foreach (var name in codeNames)
            {
                Write("case ErrorCode.");
                Write(name);
                WriteLine(":");
            }
            Indent();
            WriteLine("return true;");
            Unindent();
        }
        WriteLine("default:");
        Indent();
        WriteLine("return false;");
        Unindent();

        this.CloseBlock();

        this.CloseBlock();
    }
}
